### PR TITLE
Audit log and change in Core DISALED states and lowered NX domain log events

### PR DESCRIPTION
**Pull request by Karm**
# Audit log
Audit log, adds SINKIT_AUDIT_FILE=<path to file> and SINKIT_AUDIT_LEVEL=ALL|AUDITED|BLOCKED. The default is ALL. The log message keeps format:

```
{"timestamp":"2017/09/23 14:20:33.181003","client_ip":"127.0.0.1","domain":"zladomena.cz","action":"block"}
{"timestamp":"2017/09/23 14:20:35.713429","client_ip":"127.0.0.1","domain":"karms.biz","action":"audit"}
```
**Note that if *SINKIT_AUDIT_FILE* is unspecified, no auditing takes place, not even on stdout.**

# Error code or network error no longer makes Core DISABLED
Furthermore, Error code or network error in communication with Core is no loger a factor in DISABLED decision making.

# Testing the RC
@robcza , ```karm/sinkit-godns:1.0.3-RC4```

### CODE REVIEW

**Comment by Karm** [comment]
@rattuscz , @robcza , hmm, thinking aout the format ```YYYY/MM/DD HH:MM:SS.μs {"client_ip":"","domain":"","action":"<audit|block>"}``` again now...Isn't it weird that the timestamp is not an attribute of the JSON object? Should it be?

**Comment by Karm** [comment]
Audit works too:
```
2017/09/17 17:33:51.953517 {"client_ip":"192.168.122.1","domain":"gskpresident.tk","action":"audit"}
2017/09/17 17:33:54.517057 {"client_ip":"192.168.122.1","domain":"hanocomin.com","action":"audit"}
2017/09/17 17:33:55.024683 {"client_ip":"192.168.122.1","domain":"hdfc.pp.ru","action":"audit"}
2017/09/17 17:33:55.843752 {"client_ip":"192.168.122.1","domain":"homedeco.com.bo","action":"audit"}
2017/09/17 17:33:56.325357 {"client_ip":"192.168.122.1","domain":"hruner.com","action":"audit"}
2017/09/17 17:33:56.346336 {"client_ip":"192.168.122.1","domain":"hui-ain-apparel.tk","action":"audit"}
2017/09/17 17:33:56.724003 {"client_ip":"192.168.122.1","domain":"ice.ip64.net","action":"audit"}
2017/09/17 17:33:56.789159 {"client_ip":"192.168.122.1","domain":"ieqpiracicaba.com.br","action":"audit"}
```

**Comment by Karm** [comment]
# Tested as Cloud resolver
Audit works also in the Cloud Resolver, if it's ever needed...
```
[root@redacted /]# tail -f  /var/log/godns.audit 
2017/09/17 18:32:23.680465 {"client_ip":"my client address redacted","domain":"benimicinode.com","action":"block"}
```
Note the usage of pre-downloaded cache. The Core is contacted only because there was a hit:
```
2017/09/17 18:32:23.634363 [DEBUG] SinklistCache Get: called for key: 206cf15096b172055e7ce08aba7d60ff
2017/09/17 18:32:23.634369 [DEBUG] SinklistCache Get: key: 206cf15096b172055e7ce08aba7d60ff found value: %!t(main.tAction=3)

    Awesome, this is a hit in the pre-generated cache on Cloud Resolver ------------------- ^^^^^^^^^^^^^^

2017/09/17 18:32:23.634374 [DEBUG] Cache Get: called for key: e0e2d289b5fe0e27bad8804b80c6e990
2017/09/17 18:32:23.634382 [DEBUG] Cache Get: key: e0e2d289b5fe0e27bad8804b80c6e990 was not found.
2017/09/17 18:32:23.634389 [DEBUG] URL:>%!(EXTRA string=http://core address redacted:8080/sinkit/rest/blacklist/dns/my client address redacted/benimicinode.com/benimicinode.com)                        
```

@robcza

**Comment by rattuscz** [comment]
OK from my side, as discussed in audit log put timestamp inside json.

**Comment by robcza** [comment]
@karm log format should be json line as follows:
```{"timestamp":"YYYY/MM/DD HH:MM:SS.μs","client_ip":"","domain":"","action":"<audit|block>"}```

**Comment by Karm** [comment]
@robcza @rattuscz Updated.

**Pull request merged**
